# docker-compose.yml
version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: biblioteca
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d biblioteca"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicación Flask
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:admin@db:5432/biblioteca
      - SECRET_KEY=docker-secret-key
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: