# docker-compose.yml
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    # AÑADE ESTA SECCIÓN PARA LIMITAR LOS RECURSOS
    deploy:
      resources:
        limits:
          memory: 2G # Intenta con 2 Gigabytes de memoria como límite
        reservations:
          memory: 1G # Garantiza al menos 1 Gigabyte
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yourdb # Asegúrate de que estos valores coincidan con tu configuración
      POSTGRES_USER: youruser # Asegúrate de que estos valores coincidan con tu configuración
      POSTGRES_PASSWORD: yourpassword # Asegúrate de que estos valores coincidan con tu configuración

volumes:
  postgres_data: